services:
  sdlinkrelay_watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sdlinkrelay:
    image: ghcr.io/firstdarkdev/sdlinkrelay:latest
    container_name: "sdlinkrelay"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 6500:6500